### ISSUE TITLE
Global exclude setting not working

### ISSUE THREAD

**Issue by h8is2w8** [AtomLinter/linter-scss-lint#110]
I want to exclude some files. But Linter always runs on them. I'm sure the relative path is correct, because scss_lint command works with all exclusions. Please help. 

- Atom version: 1.3.1
- LInter version: 1.11.3
- SCSS-Lint version: 0.42.2
- Sass version: 3.4.19
- Ruby version: 2.2.1

```
scss_files: 'app/assets/stylesheets/client/*.scss'
exclude: 'app/assets/stylesheets/general/plugin-modifications/*.scss'

linters:
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
  ElsePlacement:
    enabled: false
```
