### ISSUE TITLE
Exclude setting not working

### ISSUE THREAD

**Issue by joshmedeski** [AtomLinter/linter-scss-lint#54]
I have an old legacy folder that has almost 9,000 SCSS errors. I want it excluded but the settings are not working. I've made sure the path is correct but the linter always runs on this file. Please help.

```
scss_files: 'resources/assets/sass/*.scss'

linters:
  BorderZero:
    enabled: false

  Indentation:
    exclude:
      - 'bower_components/**'
      - 'resources/assets/sass/_legacy.scss'
    severity: warning
    width: 2

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
```
