### ISSUE TITLE
Let the user decide the indention

### ISSUE THREAD

**Issue by visualcookie** [AtomLinter/linter-scss-lint#84]
Whoa, just discovered this and it drives me crazy. I got my own indention styleguide of three tabs and your plugin is suggesting spaces.

Why would you do this?

Screen of prove:
![scsslint](https://cloud.githubusercontent.com/assets/1857554/10028356/3c369aac-616c-11e5-8e8d-1144f37e960a.png)

**Comment by SpainTrain** [comment]
This has nothing to do with this plugin, that is the default for scss-lint - https://github.com/brigade/scss-lint/blob/master/config/default.yml#L88

You can create a config file to customize to your needs - https://github.com/brigade/scss-lint#configuration

For example, in your project directory you can create `.scss-lint.yml`:

```yml
linters:
  Indentation:
    character: tab
    width: 3
````

or just turn it off:

```yml
linters:
  Indentation:
    enabled: false
```
